In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
path = '/content/drive/My Drive/data/feed-views.log'

In [ ]:
df = pd.read_csv(path, sep='\t', skiprows=[2, 3], skipfooter = 2, header=None, names=['datetime', 'user'], index_col='datetime')
df.head()

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)

                              user
datetime
2020-04-17 12:01:08.463179   artem
2020-04-17 12:01:23.743946   artem
2020-04-17 12:35:52.735016   artem
2020-04-17 12:36:21.401412  oksana
2020-04-17 12:36:22.023355  oksana

In [ ]:
df.index.name = 'date_time'
df.head()

                              user
date_time
2020-04-17 12:01:08.463179   artem
2020-04-17 12:01:23.743946   artem
2020-04-17 12:35:52.735016   artem
2020-04-17 12:36:21.401412  oksana
2020-04-17 12:36:22.023355  oksana

In [ ]:
df.to_csv('data/feed-views-semicolon.log', sep=';')

In [ ]:
df.head()

                              user
date_time
2020-04-17 12:01:08.463179   artem
2020-04-17 12:01:23.743946   artem
2020-04-17 12:35:52.735016   artem
2020-04-17 12:36:21.401412  oksana
2020-04-17 12:36:22.023355  oksana

In [ ]:
df.tail()

                                 user
date_time
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel